# Generated by Django 5.0.4 on 2026-03-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_moviesdetails1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdetails1',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movieslist', to='users.streamplatformdetails1'),
        ),
    ]
